### ISSUE TITLE
Experiment with a lower RAM threshold for WebLaF

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#104]
I don't know if this will make a difference or not to the speed of VTP5, but it's worth a go. I'll do this on the LRC netbooks at school next week.

(May be linked to issue #103.)

**Comment by abdelabdalla** [comment]
Make sure that you test cpu cores threshold too

**Comment by leMingathon** [comment]
I'll try to remember... :)

**Comment by leMingathon** [comment]
Closing this for now, since we're no longer taking account of RAM.
