### ISSUE TITLE
.vtp5 folder doesn't seem to be created on Mac OS

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#106]
This is what my diagnosis has suggested - not 100% sure if it's correct though. I'm assigning it to Abdel just because he might know quite a bit about Java I/O.

**Comment by nikunjpaliwal** [comment]
We don't even know if this is fixed.

**Comment by nikunjpaliwal** [comment]
I'm also going to revert your latest commit Abdel, 'cos it may not be working right now and we can easily add it back in.

**Comment by leMingathon** [comment]
Should be fine now.
