### ISSUE TITLE
Improve thumbnail

### ISSUE THREAD

**Issue by Unueco** [vtp5/vtp5#111]
Hey guys,
I am a reading school student in year eight and I loved VTP 4 and I am happy to here we will be getting a sequel!!! But plz can u update the thumbnail cos I didn't really like the other one. Just a quick request and I really don't mind if u don't do it so yeah.

Good luck:P

**Comment by leMingathon** [comment]
Hi Rehan,

Thanks for your interest in VTP5! Could you just clarify what you mean by "updating the thumbnail" - the icon we're using is already different to the one used by VTP4.

Thanks for the feedback!

**Comment by abdelabdalla** [comment]
Hi, this is a link to our new thumbnail http://vtp5.github.io/images/vtplarge.png

**Comment by Unueco** [comment]
Great!!!
Shall I download VTP 5 now or in the next week?
Is it more or less complete???

**Comment by nikunjpaliwal** [comment]
You can download it now if you want. There are a few features that we want to add (to allow for more complex tests, for example) and there are a few things we need to flesh out a bit, but for all intents and purposes, VTP5 is usable.

**Comment by nikunjpaliwal** [comment]
By the way, we will be releasing a new version pretty soon, so you may want to wait for that.

**Comment by Unueco** [comment]
wait can the program be updated or do i have do re download

**Comment by leMingathon** [comment]
Hi Rehan,

Once you've downloaded the application, it will automatically check for updates when you start it up (as long as your computer is connected to the Internet). If it finds a newer release, it will give you a link to the releases page, where you can then download the latest version. We'll be releasing a new version either today or tomorrow, so be sure to check it out!

Thanks!

**Comment by Unueco** [comment]
guys this is a big ask but... can u add me as a contributor! I can contribute every day if I have to and do it most breaks and lunch. As of current my strongest language is JS but I am planning (I kind of already started) on starting Jquery. I don't want to edit code much but I have a ton of ideas not to mention I use VTP every day (and code the files)!!!

**Comment by Unueco** [comment]
I am already currently coming to E3 most lunches to do github anyways...

**Comment by abdelabdalla** [comment]
We thank you for your interest in helping us. At the moment, we are close to our initial release and we don't need any help. This does not mean that you can't send your ideas to us and help us with bug finding. It's great that you're writing text files for VTP5 - we're really glad for your support and would love it if you continued doing so.
