### ISSUE TITLE
Issues with legacy text files

### ISSUE THREAD

**Issue by Unueco** [vtp5/vtp5#112]
Guys upon trying to use some of the old VTP 4 files I used to use for German (i made them myself)(and yes they do work on VTP 4) I found that it didn't work on VTP 5!!! :(((((

**Comment by Unueco** [comment]
this may be just my computer and it may just be one of those temporary issues that work annoyingly afterwards but i dont know:\

**Comment by nikunjpaliwal** [comment]
Could you email/upload the text file that wasn't working please? My email is k00745@reading-school.co.uk.

**Comment by Unueco** [comment]
k will do ASAP

**Comment by Unueco** [comment]
sorry all!
I will get it to u soon

**Comment by nikunjpaliwal** [comment]
You still haven't sent it to me.
