### ISSUE TITLE
Support for Chinese and other such languages

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#125]

**Comment by Unueco** [comment]
Look I do know some Chinese and trust me when I say you don't want to do this. Firstly given the fact that the complexity is sometimes off the scale (except with short building block words like huo, mu and kou). Also there is the fact that there would have to be support for both Cantonese and Mandarin both in simplified and traditional form however the idea to support other languages is a good one as long as they are not too complex in things like characters and stuffz!

**Comment by leMingathon** [comment]
I _am_ Chinese... I'll make sure this works, don't worry...

**Comment by leMingathon** [comment]
Also, the file doesn't necessarily have to contain both traditional and simplified, or both Mandarin and Chinese.
