### ISSUE TITLE
Add a special case for text in brackets

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#127]
E.g.:
- Add an option to ignore stuff in brackets
- "Separate out" bracketed text in answer, as though it were separated by a slash

**Comment by Unueco** [comment]
Yeah this is quite a generic problem when it comes to most users (especially in 8W) when they r using VTP for tests and stuff. Usually it causes a ton of confusion with the additional info in the brackets and this usually ends in the person getting a slightly inaccurate test result... basically this needs to be fixed (obviously after your GCSE exams though)!

**Comment by leMingathon** [comment]
Thanks for the feedback - we'll try and get it done as soon as possible... (Not sure when that'll be!)

**Comment by Unueco** [comment]
There's no point worrying bout all this stuff now. You have exams coming so you shouldnt really worry bout the development side. Instead doing things like suggesting things to do after exam time would be good for now.

At the moment I plan to run some quick surveys on my class to see what they would like in VTP.
