### ISSUE TITLE
Implement a survey feature where users can suggest new features for VTP

### ISSUE THREAD

**Issue by Unueco** [vtp5/vtp5#128]
Rather put this one on hold for now until exams are over...for everyone's sake!

**Comment by leMingathon** [comment]
We already have this form (which you may have already used?): https://docs.google.com/forms/d/1TK5I8IXvcCES6Xk1yRAZPRAreRLo9Sjm2o_vx6MA4hY/edit

You can also get to it by clicking the "About" button in VTP5 and then clicking "Send feedback".

**Comment by nikunjpaliwal** [comment]
Considering we already have something like this, I'm closing it.

**Comment by BadgerBoy1002** [comment]
do we?
