### ISSUE TITLE
Make a VTP Wikipedia page

### ISSUE THREAD

**Issue by Unueco** [vtp5/vtp5#129]
Yh I know we already have a wiki but I think having a Wikipedia page would be a good step up (considering the fact we WANT funding)! Anyways I know most think anyone can edit Wikipedia but this isn't 100% true. In fact u can only edit all pages if you have edited a lot of articles and you have had account for a certain period. I am one of those users so if you want I could make one!

**Comment by abdelabdalla** [comment]
The thing about needing an account is not true. Anyone can edit it. There are some pages that are protected and do require an account though

**Comment by Unueco** [comment]
That's what I mean
I know I wasn't that clear
But that's what I meant by pages you can't edit!

**Comment by abdelabdalla** [comment]
From Wikipedia:
Please do not submit articles that are about:

yourself, your company or organization. (Conflict of Interest)
your friend, your band, or your website. (Notability)
your vendettas or campaigns. (Neutrality)

Our program is not notable enough to have an article at this time
