### ISSUE TITLE
Long words in flashcards need to resize

### ISSUE THREAD

**Issue by abdelabdalla** [vtp5/vtp5#130]
[Link to screenshot of issue](http://i.imgur.com/R2NWjR5.png?1)

**Comment by leMingathon** [comment]
Which device were you using? For me, the word just wraps...

**Comment by abdelabdalla** [comment]
New tablet...I think a trend is emerging

**Comment by abdelabdalla** [comment]
there are no spaces in the example so it was treated as one word
