### ISSUE TITLE
The new release isn't working

### ISSUE THREAD

**Issue by Unueco** [vtp5/vtp5#136]
For some of the people in my class have had problems accessing the program including me! This is with people who updated yesterday. The problem is that when entering the program you are unable to do so and this message pops up:
A JAVA EXCEPTION HAS OCCURRED!!!!!

This is a big problem as anyone who updates the program (and hasn't heard of using the old version ever) are emailing me to find a solution

HELPPPPPPPPP!

**Comment by abdelabdalla** [comment]
We compiled the programming using Java 8. All school computers have Java 7. We will be releasing a fix soon

**Comment by abdelabdalla** [comment]
Can you also tell people to email us directly so we can actually help them

**Comment by leMingathon** [comment]
The release should be fixed now. Thanks for your patience.
