### ISSUE TITLE
Add a timer function for each question.

### ISSUE THREAD

**Issue by nikunjpaliwal** [vtp5/vtp5#19]

**Comment by duckifyz** [comment]
Abdel is working on the CSV format . Maybe he can ask one of the others to help implement it into the GUI.

**Comment by abdelabdalla** [comment]
I need a volunteer to add a timer into the program. It has to take in the time allowed from a variable(the variable is in CSVTF.jar atm but it can be changed) and set the timer to that amount of time. It also needs to disable the timer if the time allowed is 0.
