### ISSUE TITLE
Move GUI over to JavaFX 8.

### ISSUE THREAD

**Issue by nikunjpaliwal** [vtp5/vtp5#21]
See this for more info: http://docs.oracle.com/javase/8/javase-clienttechnologies.htm

This would require a rewrite of the GUI aspects and also update to Java 8, but JavaFX is designed to be the successor to Swing and is better in pretty much every way. This would probably not be done in the foreseeable future but is something to keep in mind.

**Comment by abdelabdalla** [comment]
It will be way too time consuming to re-write most of the program so I don't think this is a good idea

**Comment by leMingathon** [comment]
We *could* do this over the summer - we don't have to do it right now... I think we should keep this open.
