### ISSUE TITLE
Create an EXE file with the JRE bundled.

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#24]
This is so end users don't need to have Java already installed on their computer.

**Comment by duckifyz** [comment]
I don't think we should have two versions. It makes the user confused. Even if it makes the file size 30 MB instead of 4 as it is at the moment, it'll be objectively better.

**Comment by leMingathon** [comment]
Hmm... I don't know - I doubt it'll be that confusing. For this particular issue, we should probably just ask people what they think.

**Comment by duckifyz** [comment]
Agreed, we can ask the teachers as they'll be the  ones distributing the program.

**Comment by abdelabdalla** [comment]
Slight issue http://stackoverflow.com/a/15620253
We need to decide if it is worth creating an installer for VTP5 or if we should tell people to download Java

**Comment by leMingathon** [comment]
Is there still any point in doing this?

**Comment by abdelabdalla** [comment]
I will put a notice on the Wiki homepage telling people that they need Java.

**Comment by duckifyz** [comment]
I'm working on creating a .exe file with JRE. It's not urgent, but it is still an issue.

**Comment by leMingathon** [comment]
Is this done now?

**Comment by abdelabdalla** [comment]
I believe so
