### ISSUE TITLE
Create sound prompts.

### ISSUE THREAD

**Issue by duckifyz** [vtp5/vtp5#39]

**Comment by abdelabdalla** [comment]
We need sounds for:
* Victory(Above 90%)
* Defeat(Below 90%)
* Correct Answer
* Wrong Answer
* Mr Cooper shouting if you haven't done well(Below 50%)?

**Comment by duckifyz** [comment]
Will do. Just doing #16 atm.

**Comment by duckifyz** [comment]
Unless we want to use an external library, only wav file will be playable.

**Comment by abdelabdalla** [comment]
I can't see a problem with wav. We might have to convert some files but that's about it

**Comment by duckifyz** [comment]
Done?
