### ISSUE TITLE
Create a settings file which saves the user's preferences

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#46]
Settings is likely to get quite big soon, so this'll be quite useful...

**Comment by leMingathon** [comment]
Yousuf, do you want to do this?

**Comment by duckifyz** [comment]
I've done this before, so once I've fixed the sorting, I could work on this.

**Comment by leMingathon** [comment]
Also, make more settings

**Comment by duckifyz** [comment]
This is pretty much finished. Yousuf created the settings file algorithms and most of the settings and I added a few more. All we need now is a setting for background colour and dynamic colour changing.

**Comment by leMingathon** [comment]
Done
