### ISSUE TITLE
Implement local leaderboard

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#52]

**Comment by duckifyz** [comment]
This ties in with issue #46 so I'm assigning it to Yousuf for now.

**Comment by TheOnlyYoumed** [comment]
Creating TestResult object so that progress can be saved.

**Comment by leMingathon** [comment]
What still needs to be done:
* Implement support for multiple files.
* Save the initial number of cards that the user selects and only display the results for that particular number of cards.
