### ISSUE TITLE
Add splash screen.

### ISSUE THREAD

**Issue by duckifyz** [vtp5/vtp5#56]
http://docs.oracle.com/javase/tutorial/uiswing/misc/splashscreen.html

**Comment by leMingathon** [comment]
Postponed this.

**Comment by leMingathon** [comment]
I'll look into this as well.

**Comment by nikunjpaliwal** [comment]
Cheers.

**Comment by nikunjpaliwal** [comment]
It works but it needs me to export it. But yay :)
