### ISSUE TITLE
Create a variable in the configs file saving the path of the directory the user last used

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#57]

**Comment by abdelabdalla** [comment]
Im wondering if this has been completed because whenever i go to import a file, it opens the last used directory

**Comment by leMingathon** [comment]
Not when you restart the program.

**Comment by abdelabdalla** [comment]
Woops. never mind. Turns out i had the file in my documents and not their usual place

**Comment by TheOnlyYoumed** [comment]
Finally....
