### ISSUE TITLE
Let user log in and access Sharepoint files and use the text files directly from there.

### ISSUE THREAD

**Issue by nikunjpaliwal** [vtp5/vtp5#62]
Perhaps using JEditorPane or a web parser.

**Comment by abdelabdalla** [comment]
I am planning on having all the txt and csv files on the website so it can be accessed by anyone. I also wanted a way for people to submit files

**Comment by duckifyz** [comment]
I don't think this is a good idea (Abdel's one). Maybe hosting files, but definitely not submitting files. Also, the point is to automatically retrieve the files from the Sharepoint API and then let  the user choose them.

**Comment by abdelabdalla** [comment]
https://code.google.com/p/java-sharepoint-library/
http://www.javaworld.com/article/2078906/enterprise-java/java-tip-consuming-sharepoint-web-services-with-a-java-client.html?null

**Comment by abdelabdalla** [comment]
This might not be useful if we plan to host the file ourselves
