### ISSUE TITLE
Support Greek characters

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#64]
We need to use the "Symbol" font family, because that's what's used on VTP4.

**Comment by abdelabdalla** [comment]
There is a greek ubuntu font available
http://font.ubuntu.com/#charset-greek

**Comment by leMingathon** [comment]
- http://unicode.org/charts/PDF/U0370.pdf:
  - Uppercase: \u0391 to \u03A9 EXCEPT \u03A2
  - Lowercase: \u03B1 to \u03C9
- http://unicode-table.com/en/:
  - Uppercase: \u0041 to \u005A
  - Lowercase: \u0061 to \u007A

**Comment by leMingathon** [comment]
http://unicode.org/Public/MAPPINGS/VENDORS/ADOBE/symbol.txt

**Comment by leMingathon** [comment]
Closing this for now...
