### ISSUE TITLE
Altered alpha value creates a few small visual bugs

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#73]
I'll try to either take a screenshot, or (if I'm well enough) show you at school...

**Comment by duckifyz** [comment]
I think *you* fixed the biggest of these, where the button panel would replicate. I wasn't aware of any others.

**Comment by leMingathon** [comment]
The biggest bug is that there is duplication on the finishPanel.

**Comment by abdelabdalla** [comment]
I found that the issue in the finishpanel goes away when i opened settings

**Comment by leMingathon** [comment]
Not completely resolved yet (there are other bugs)

**Comment by abdelabdalla** [comment]
Oh yeah. I forgot about the butt

**Comment by abdelabdalla** [comment]
I am awesome
