### ISSUE TITLE
Add ability to send from multiple email types

### ISSUE THREAD

**Issue by nikunjpaliwal** [vtp5/vtp5#80]

**Comment by leMingathon** [comment]
Put this on hold for now - Abdel's thinking of having some sort of Sharepoint verification thing.

**Comment by nikunjpaliwal** [comment]
As far as I know, this hasn't been implemented yet.

**Comment by abdelabdalla** [comment]
What email types do you want?

**Comment by nikunjpaliwal** [comment]
ALL THE EMAIL TYPES! :)

**Comment by BadgerBoy1002** [comment]
As far as I know a lot of year 8's use Gmail...
