### ISSUE TITLE
VTP5 may lag or freeze completely on slower machines (e.g. LRC netbooks)

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#82]
This happens particularly when you try to save a progress file.

**Comment by abdelabdalla** [comment]
We can look at the system specs and disable certain settings to speed it up

**Comment by leMingathon** [comment]
I've had the program freeze/take a long time to do something on the LRC netbooks in two situations:
* After pressing Enter/OK (possibly due to Collections.shuffle()?)
* When trying to save progress

**Comment by abdelabdalla** [comment]
The program seems to only lag when you press enter/ok the first time. I am on a fast computer so this may be more serious on other devices

**Comment by duckifyz** [comment]
This seems to be done so closing for now.
