### ISSUE TITLE
Apply for OR funding

### ISSUE THREAD

**Issue by leMingathon** [vtp5/vtp5#96]

**Comment by leMingathon** [comment]
Nik/Yousuf - could one of you do this?

**Comment by Unueco** [comment]
Has the deadline for this funding closed

**Comment by Unueco** [comment]
We are more likely to get OR funding if we highlight the fact that this is for a program used by the Reading School Classics Department!

**Comment by abdelabdalla** [comment]
Urm what do you mean by "we"?

**Comment by nikunjpaliwal** [comment]
We've already applied for funding.
